#theme: jekyll-theme-cayman
remote_theme: just-the-docs/just-the-docs
title: samuels shenanigans 
description: programming and technology blog


author:
  name: Samuel Kriikkula
  avatar: "/assets/b2.jpg"
