#theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: samuels shenanigans 
description: programming and technology blog


author:
  name: Samuel Kriikkula
  avatar: "/assets/b2.jpg"
